/*
 *  This file is part of ZiggyStardust.
 *
 *  ZiggyStardust is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ZiggyStardust is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.wisc.csvParser.plugins;

/**
 *
 * @author  user
 */
public class JDialogDateParserCSIArray extends java.awt.Dialog {
    
    DateTimeParserCSI parser;
    
    /** Creates new form JDialogDateParserCSIArray */
    public JDialogDateParserCSIArray(java.awt.Frame parent, boolean modal,DateTimeParserCSI parser) {
        super(parent, modal);
        initComponents();
        
        this.parser = parser;
        
        yearTF.setText(Integer.toString(parser.getYearIndex()));
        daynumTF.setText(Integer.toString(parser.getDaynumIndex()));
        
        if(parser.getTimeIndex() > -1){
            hasTimeCB.setSelected(true);
            timeTF.setEnabled(true);
            timeTF.setText(Integer.toString(parser.getTimeIndex()));
        }else{
            timeTF.setText("");
        }

        if (parser.getSecondsIndex() > -1) {
            hasSecondsCB.setSelected(true);
            secondsTF.setEnabled(true);
            secondsTF.setText(Integer.toString(parser.getSecondsIndex()));
        } else {
            secondsTF.setText("");
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        asdfasdf = new javax.swing.JLabel();
        yearTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        daynumTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        timeTF = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        hasTimeCB = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        secondsTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hasSecondsCB = new javax.swing.JCheckBox();

        setLocationRelativeTo(this);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        asdfasdf.setText("Year Column Number:");

        yearTF.setText("1");

        jLabel1.setText("Daynum Column Number:");

        daynumTF.setText("2");

        jLabel2.setText("Time Column Number:");

        timeTF.setText("3");
        timeTF.setEnabled(false);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        hasTimeCB.setText("Has Time");
        hasTimeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasTimeCBActionPerformed(evt);
            }
        });
        hasTimeCB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hasTimeCBPropertyChange(evt);
            }
        });

        jLabel3.setText("<html>IMPORTANT: All column indexes are zero indexed. This<br />\nmeans the first column is column 0, the second is column 1,<br />\netc.</html>\n");

        secondsTF.setText("4");

        jLabel4.setText("Seconds Column Number:");

        hasSecondsCB.setText("Has Seconds");
        hasSecondsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasSecondsCBActionPerformed(evt);
            }
        });
        hasSecondsCB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hasSecondsCBPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(asdfasdf)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(timeTF)
                                    .addComponent(yearTF)
                                    .addComponent(daynumTF, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(secondsTF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cancelButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasSecondsCB)
                            .addComponent(saveButton)
                            .addComponent(hasTimeCB)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asdfasdf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daynumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasTimeCB)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(hasSecondsCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int yearIndex = -1;
        int daynumIndex = -1;
        int timeIndex = -1;
        int secondsIndex = -1;
        
        
        try{
            yearIndex = Integer.parseInt(yearTF.getText());
            daynumIndex = Integer.parseInt(daynumTF.getText());
            if (hasSecondsCB.isSelected()) {
                secondsIndex = Integer.parseInt(secondsTF.getText());
            }
            if(hasTimeCB.isSelected()){
                timeIndex = Integer.parseInt(timeTF.getText());
            }
            
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null,"Indexes must be positive integers or zero.");
            return;
        }
        
        if(yearIndex < 0 || daynumIndex < 0 || (timeIndex < 0 && hasTimeCB.isSelected()) ||
                (secondsIndex < 0 && hasSecondsCB.isSelected())){
            javax.swing.JOptionPane.showMessageDialog(null,
                    "All indexes must be integers zero or greater.");
            return;
        }
        
        parser.setDaynumIndex(daynumIndex);
        parser.setTimeIndex(timeIndex);
        parser.setYearIndex(yearIndex);
        parser.setSecondsIndex(secondsIndex);
        
        //if we've gotten here, user wants to exit and input is all ok.
        setVisible(false);
        dispose();

        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void hasTimeCBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hasTimeCBPropertyChange
        timeTF.setEnabled(hasTimeCB.isSelected());
}//GEN-LAST:event_hasTimeCBPropertyChange

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void hasTimeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasTimeCBActionPerformed
        timeTF.setEnabled(hasTimeCB.isSelected());
    }//GEN-LAST:event_hasTimeCBActionPerformed

    private void hasSecondsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasSecondsCBActionPerformed
        secondsTF.setEnabled(hasSecondsCB.isSelected());
    }//GEN-LAST:event_hasSecondsCBActionPerformed

    private void hasSecondsCBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hasSecondsCBPropertyChange
        secondsTF.setEnabled(hasSecondsCB.isSelected());
    }//GEN-LAST:event_hasSecondsCBPropertyChange

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asdfasdf;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField daynumTF;
    private javax.swing.JCheckBox hasSecondsCB;
    private javax.swing.JCheckBox hasTimeCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField secondsTF;
    private javax.swing.JTextField timeTF;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables
    
}
