/*
 *  This file is part of ZiggyStardust.
 *
 *  ZiggyStardust is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ZiggyStardust is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.wisc.csvParser;
import java.awt.Component;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author  lawinslow
 */
public class SettingsDialog extends javax.swing.JDialog {
    
    /** Creates new form NewJDialog */
    public SettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        autoSaveCB.setSelected(GlobalProgramSettings.getAutoSaveSettings());
        autoLoadCB.setSelected(GlobalProgramSettings.getAutoLoadSettings());
        settingsFilePath.setText(GlobalProgramSettings.getSettingsFilePath());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        autoSaveCB = new javax.swing.JCheckBox();
        settingsFilePath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        selectFileButton = new javax.swing.JButton();
        autoLoadCB = new javax.swing.JCheckBox();
        okbutton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        vocabProviderSettingsButton = new javax.swing.JButton();
        notificationProviderSettings = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        autoSaveCB.setText("Automatically save settings.");

        jLabel1.setText("Settings File:");

        selectFileButton.setText("....");
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        autoLoadCB.setText("Automatically load settings on program startup");

        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        vocabProviderSettingsButton.setText("Vocabulary Provider Settings");
        vocabProviderSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vocabProviderSettingsButtonActionPerformed(evt);
            }
        });

        notificationProviderSettings.setText("Event Notification Provider Settings");
        notificationProviderSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationProviderSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(autoSaveCB))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(autoLoadCB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(settingsFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectFileButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(vocabProviderSettingsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notificationProviderSettings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autoSaveCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(selectFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoLoadCB)
                .addGap(18, 18, 18)
                .addComponent(vocabProviderSettingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificationProviderSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okbutton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        //simply exit
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        GlobalProgramSettings.setAutoLoadSettings(autoLoadCB.isSelected());
        GlobalProgramSettings.setAutoSaveSettings(autoSaveCB.isSelected());
        GlobalProgramSettings.setSettingsFilePath(settingsFilePath.getText());
        GlobalProgramSettings.saveSettings();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_okbuttonActionPerformed

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        JFileChooser f = new JFileChooser();
        f.setDialogType(JFileChooser.SAVE_DIALOG);
        f.showSaveDialog(this);
        if(f.getSelectedFile()!= null)
            settingsFilePath.setText(f.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_selectFileButtonActionPerformed
    /**
     * Displays, if available, the settings dialog for the global vocab provider
     * 
     * @param evt
     */
    private void vocabProviderSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vocabProviderSettingsButtonActionPerformed
        javax.swing.JDialog frame = new javax.swing.JDialog(this);
        frame.setSize(256,256);
        frame.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(GlobalProgramSettings.vocabProvider.getSettingsJPanel());
        frame.pack();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
}//GEN-LAST:event_vocabProviderSettingsButtonActionPerformed

    private void notificationProviderSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationProviderSettingsActionPerformed
        javax.swing.JDialog frame = new javax.swing.JDialog(this);
        frame.setSize(256,256);
        frame.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(GlobalProgramSettings.provider.getStatusJPanel());
        frame.pack();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
        
}//GEN-LAST:event_notificationProviderSettingsActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SettingsDialog dialog = new SettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoLoadCB;
    private javax.swing.JCheckBox autoSaveCB;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton notificationProviderSettings;
    private javax.swing.JButton okbutton;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JTextField settingsFilePath;
    private javax.swing.JButton vocabProviderSettingsButton;
    // End of variables declaration//GEN-END:variables
    
}
